# Generated by Django 3.1 on 2021-07-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTableForPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_price', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
                ('courses', models.ManyToManyField(related_name='courses', through='students.ExtraTableForPayment', to='courses.Course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.group')),
            ],
        ),
        migrations.AddField(
            model_name='extratableforpayment',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_price', to='students.student'),
        ),
    ]
