# Generated by Django 3.1 on 2021-07-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skidka', models.IntegerField()),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_payments', to='students.student')),
            ],
        ),
    ]
