# Generated by Django 3.1 on 2021-07-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='title',
        ),
    ]
