# Generated by Django 3.1 on 2021-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_remove_expenses_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date_of_add',
            field=models.DateField(auto_now=True),
        ),
    ]
